# User guide: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: fys5429

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.11
  - numpy
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - pip

  - pip:
    - torch 
    - torchvision
    - ratinabox
