# User guide: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: project-1

channels:
  - defaults

dependencies:
  - python>=3.11
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas

  - pip:
    - scikit-learn
    - torch 
    - torchvision
    - ratinabox

